use super::ClipboardBackend;
use crate::{ClipboardData, ClipboardReason, NativeGeneration};
use objc2::{ClassType, msg_send, sel};
use objc2::{
    rc::{Retained, autoreleasepool},
    runtime::ProtocolObject,
};
use objc2_app_kit::{
    NSPasteboard, NSPasteboardAccessBehavior, NSPasteboardTypeString, NSPasteboardWriting,
};
use objc2_foundation::{NSArray, NSString};

const PRIVATE_TYPES: [&str; 3] = [
    "org.nspasteboard.TransientType",
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.AutoGeneratedType",
];

pub struct MacOsClipboardBackend;

impl MacOsClipboardBackend {
    pub fn connect() -> Result<Self, ClipboardReason> {
        Ok(Self)
    }

    fn pasteboard() -> Result<Retained<NSPasteboard>, ClipboardReason> {
        // A daemon outside a GUI login session can receive nil despite the API's non-null contract.
        let pasteboard: Option<Retained<NSPasteboard>> =
            unsafe { msg_send![NSPasteboard::class(), generalPasteboard] };
        pasteboard.ok_or(ClipboardReason::BackendUnavailable)
    }

    fn generation_for(pasteboard: &NSPasteboard) -> Result<NativeGeneration, ClipboardReason> {
        generation_from_change_count(pasteboard.changeCount())
    }

    fn capture_from(
        pasteboard: &NSPasteboard,
        max_bytes: usize,
    ) -> Result<ClipboardData, ClipboardReason> {
        // AppKit exports this process-lifetime constant from an extern static.
        let string_type = unsafe { NSPasteboardTypeString };
        let types = pasteboard
            .types()
            .ok_or_else(|| access_failure(pasteboard))?;
        if types.is_empty() {
            return Ok(ClipboardData::Empty);
        }
        if types
            .iter()
            .any(|pasteboard_type| is_private_type(&pasteboard_type.to_string()))
        {
            return Err(ClipboardReason::PrivateContent);
        }
        if !types
            .iter()
            .any(|pasteboard_type| pasteboard_type.isEqualToString(string_type))
        {
            return Err(ClipboardReason::UnsupportedFormat);
        }
        let text = pasteboard
            .stringForType(string_type)
            .ok_or_else(|| access_failure(pasteboard))?;
        decode_text(&text.to_string(), max_bytes)
    }

    fn write_to(
        pasteboard: &NSPasteboard,
        data: &ClipboardData,
    ) -> Result<NativeGeneration, ClipboardReason> {
        let text = match data {
            ClipboardData::Text(bytes) => {
                Some(std::str::from_utf8(bytes).map_err(|_| ClipboardReason::InvalidUtf8)?)
            }
            ClipboardData::Empty => None,
            ClipboardData::Unavailable(reason) => return Err(*reason),
        };
        if access_is_denied(pasteboard) {
            return Err(ClipboardReason::PermissionDenied);
        }
        let objects = text.map(|text| {
            let object: Retained<ProtocolObject<dyn NSPasteboardWriting>> =
                ProtocolObject::from_retained(NSString::from_str(text));
            NSArray::from_retained_slice(&[object])
        });

        generation_from_change_count(pasteboard.clearContents())?;
        if let Some(objects) = objects {
            if !pasteboard.writeObjects(&objects) {
                return Err(access_failure(pasteboard));
            }
        }
        Self::generation_for(pasteboard)
    }

    fn apply_to(
        pasteboard: &NSPasteboard,
        expected_generation: NativeGeneration,
        data: &ClipboardData,
    ) -> Result<NativeGeneration, ClipboardReason> {
        if Self::generation_for(pasteboard)? != expected_generation {
            return Err(ClipboardReason::DestinationChanged);
        }
        Self::write_to(pasteboard, data)
    }
}

impl ClipboardBackend for MacOsClipboardBackend {
    fn initialize(&mut self) -> Result<NativeGeneration, ClipboardReason> {
        autoreleasepool(|_| {
            let pasteboard = Self::pasteboard()?;
            if access_is_denied(&pasteboard) {
                return Err(ClipboardReason::PermissionDenied);
            }
            Self::generation_for(&pasteboard)
        })
    }

    fn generation(&mut self) -> Result<NativeGeneration, ClipboardReason> {
        autoreleasepool(|_| {
            let pasteboard = Self::pasteboard()?;
            Self::generation_for(&pasteboard)
        })
    }

    fn capture(&mut self, max_bytes: usize) -> Result<ClipboardData, ClipboardReason> {
        autoreleasepool(|_| {
            let pasteboard = Self::pasteboard()?;
            Self::capture_from(&pasteboard, max_bytes)
        })
    }

    fn apply(
        &mut self,
        expected_generation: NativeGeneration,
        data: &ClipboardData,
    ) -> Result<NativeGeneration, ClipboardReason> {
        autoreleasepool(|_| {
            let pasteboard = Self::pasteboard()?;
            Self::apply_to(&pasteboard, expected_generation, data)
        })
    }
}

fn generation_from_change_count(change_count: isize) -> Result<NativeGeneration, ClipboardReason> {
    u64::try_from(change_count)
        .map(NativeGeneration::new)
        .map_err(|_| ClipboardReason::BackendUnavailable)
}

fn access_failure(pasteboard: &NSPasteboard) -> ClipboardReason {
    if access_is_denied(pasteboard) {
        ClipboardReason::PermissionDenied
    } else {
        ClipboardReason::BackendUnavailable
    }
}

fn access_is_denied(pasteboard: &NSPasteboard) -> bool {
    let responds: bool = unsafe { msg_send![pasteboard, respondsToSelector: sel!(accessBehavior)] };
    if !responds {
        return false;
    }
    let behavior: isize = unsafe { msg_send![pasteboard, accessBehavior] };
    behavior == NSPasteboardAccessBehavior::AlwaysDeny.0
}

fn is_private_type(pasteboard_type: &str) -> bool {
    PRIVATE_TYPES.contains(&pasteboard_type)
}

fn decode_text(text: &str, max_bytes: usize) -> Result<ClipboardData, ClipboardReason> {
    let normalized = normalize_line_endings(text);
    if normalized.len() > max_bytes {
        return Err(ClipboardReason::Oversize);
    }
    if normalized.is_empty() {
        Ok(ClipboardData::Empty)
    } else {
        ClipboardData::text(normalized.into_bytes())
    }
}

fn normalize_line_endings(text: &str) -> String {
    if !text.as_bytes().contains(&b'\r') {
        return text.to_owned();
    }
    text.replace("\r\n", "\n").replace('\r', "\n")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn recognized_private_types_are_never_exported() {
        for pasteboard_type in PRIVATE_TYPES {
            assert!(is_private_type(pasteboard_type));
        }
        assert!(!is_private_type("public.utf8-plain-text"));
    }

    #[test]
    fn text_is_bounded_after_utf8_and_line_normalization() {
        assert_eq!(
            decode_text("first\r\nsecond", 12).unwrap(),
            ClipboardData::text(b"first\nsecond".to_vec()).unwrap()
        );
        assert_eq!(decode_text("é", 1), Err(ClipboardReason::Oversize));
        assert_eq!(decode_text("", 0).unwrap(), ClipboardData::Empty);
    }

    #[test]
    fn negative_change_count_is_backend_failure() {
        assert_eq!(
            generation_from_change_count(-1),
            Err(ClipboardReason::BackendUnavailable)
        );
        assert_eq!(
            generation_from_change_count(0).unwrap(),
            NativeGeneration::new(0)
        );
    }

    #[test]
    fn native_unique_pasteboard_covers_text_empty_privacy_and_destination_race() {
        let pasteboard = NSPasteboard::pasteboardWithUniqueName();
        let text = ClipboardData::text("lan-mouse 😀\nclipboard".as_bytes().to_vec()).unwrap();

        let baseline = MacOsClipboardBackend::generation_for(&pasteboard).unwrap();
        MacOsClipboardBackend::apply_to(&pasteboard, baseline, &text).unwrap();
        assert_eq!(
            MacOsClipboardBackend::capture_from(&pasteboard, 1024).unwrap(),
            text
        );

        let baseline = MacOsClipboardBackend::generation_for(&pasteboard).unwrap();
        MacOsClipboardBackend::apply_to(&pasteboard, baseline, &ClipboardData::Empty).unwrap();
        assert_eq!(
            MacOsClipboardBackend::capture_from(&pasteboard, 1024).unwrap(),
            ClipboardData::Empty
        );

        let stale = MacOsClipboardBackend::generation_for(&pasteboard).unwrap();
        MacOsClipboardBackend::write_to(
            &pasteboard,
            &ClipboardData::text(b"destination changed".to_vec()).unwrap(),
        )
        .unwrap();
        assert_eq!(
            MacOsClipboardBackend::apply_to(&pasteboard, stale, &ClipboardData::Empty),
            Err(ClipboardReason::DestinationChanged)
        );

        let private_type = NSString::from_str(PRIVATE_TYPES[0]);
        let private_value = NSString::from_str("secret");
        pasteboard.clearContents();
        assert!(pasteboard.setString_forType(&private_value, &private_type));
        assert_eq!(
            MacOsClipboardBackend::capture_from(&pasteboard, 1024),
            Err(ClipboardReason::PrivateContent)
        );

        let unsupported_type = NSString::from_str("public.png");
        let unsupported_value = NSString::from_str("not text");
        pasteboard.clearContents();
        assert!(pasteboard.setString_forType(&unsupported_value, &unsupported_type));
        assert_eq!(
            MacOsClipboardBackend::capture_from(&pasteboard, 1024),
            Err(ClipboardReason::UnsupportedFormat)
        );
    }
}
